[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.nox
  | build
  | venv
  | dist
  | \.eggs
)/
'''

[tool.isort]
profile = "black"
src_paths = ["dfp", "tests"]
skip=[".tox",".nox","venv","build","dist","resources","model","log"]
