[tool.black]
line-length = 79
include = '''
/(
    ^setup\.py
  | dfp
  | tests
)/
'''
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.nox
  | __pycache__
  | \.pyc$
  | \.ipynb$
  | \.md$
  | build
  | venv
  | dist
  | \.eggs
)/
'''

[tool.isort]
profile = "black"
src_paths = ["dfp", "tests"]
skip=[".tox",".nox","venv","build","dist","resources","model","log"]
