[tool.black]
line-length = 79
include = '''
/(
    dfp
  | tests
)/
'''
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.nox
  | __pycache__
  | \.pyc$
  | \.ipynb$
  | \.md$
  | build
  | venv
  | dist
  | \.eggs
)/
'''

[tool.isort]
profile = "black"
